spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mariadb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

security:
  jwt:
    token:
      security-key: secret-key
      expiration-length: 3600000

shop:
  upload:
    path: C:\update

UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token

server:
  port: 8080